# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default=None, max_length=30)),
                ('Nickname', models.CharField(default=None, max_length=30)),
                ('Telephone', models.CharField(default=None, max_length=11)),
                ('Password', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
