# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('GoodsAmount', models.PositiveIntegerField()),
                ('GoodsName', models.CharField(max_length=30)),
                ('GoodsPrice', models.CharField(max_length=30)),
                ('GoodsPicture', models.ImageField(upload_to='goods')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GOODSCATAGORY',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'goodsCatagory',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='GoodsCatagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GOODSCATAGORY'),
        ),
    ]
