# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20160608_0635'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table='goods',
        ),
        migrations.AlterModelTable(
            name='goodscatagory',
            table='goodsCatagory',
        ),
    ]
